// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAth7EjHSTd8qVdDrfj4MT8V7wtCcFvYKE',
    appId: '1:818055980545:web:9615f23e6001bd9f108200',
    messagingSenderId: '818055980545',
    projectId: 'comrades-5e3ce',
    authDomain: 'comrades-5e3ce.firebaseapp.com',
    storageBucket: 'comrades-5e3ce.appspot.com',
    measurementId: 'G-FN0SL8BEC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTr-J7YgqWyrkmUvKhuhUEFTPUxQKqAxE',
    appId: '1:818055980545:android:f6b4f27c532a0612108200',
    messagingSenderId: '818055980545',
    projectId: 'comrades-5e3ce',
    storageBucket: 'comrades-5e3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaSJzZWxwBGYkw83_KTs24PFcTsd7lRg',
    appId: '1:818055980545:ios:7f3a1ff2a4571f8c108200',
    messagingSenderId: '818055980545',
    projectId: 'comrades-5e3ce',
    storageBucket: 'comrades-5e3ce.appspot.com',
    androidClientId: '818055980545-ri95qr1qcvm87hqgg9cnr65jb2014ofj.apps.googleusercontent.com',
    iosClientId: '818055980545-mr3s4sjmo3n6m202uvo722j1kcgcg1pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.comrades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFaSJzZWxwBGYkw83_KTs24PFcTsd7lRg',
    appId: '1:818055980545:ios:7f3a1ff2a4571f8c108200',
    messagingSenderId: '818055980545',
    projectId: 'comrades-5e3ce',
    storageBucket: 'comrades-5e3ce.appspot.com',
    androidClientId: '818055980545-ri95qr1qcvm87hqgg9cnr65jb2014ofj.apps.googleusercontent.com',
    iosClientId: '818055980545-mr3s4sjmo3n6m202uvo722j1kcgcg1pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.comrades',
  );
}
